In [3]:
##########################################################################################
#                                                                                        #
#  888888b.  8888888 .d88888b.   .d8888b.     .d8888b.   .d8888b.      d8888      d8888  #
#  888  "88b   888  d88P" "Y88b d88P  Y88b   d88P  Y88b d88P  Y88b    d8P888     d8P888  #
#  888  .88P   888  888     888 Y88b.        888        888          d8P 888    d8P 888  #
#  8888888K.   888  888     888  "Y888b.     888d888b.  888d888b.   d8P  888   d8P  888  #
#  888  "Y88b  888  888     888     "Y88b.   888P "Y88b 888P "Y88b d88   888  d88   888  #
#  888    888  888  888     888       "888   888    888 888    888 8888888888 8888888888 #
#  888   d88P  888  Y88b. .d88P Y88b  d88P   Y88b  d88P Y88b  d88P       888        888  #
#  8888888P" 8888888 "Y88888P"   "Y8888P"     "Y8888P"   "Y8888P"        888        888  #
#                                                                                        # 
##########################################################################################
#
# Python Refresher
#
##########################################################################################

4

In [ ]:
##################################################################################################################
#
# YouDo:
#    1) Make a copy of this notebook with your name as a suffix:  
#           M0_Python_Refresher_FirstLast
#    2) Do all work in this new notebook.
#
##################################################################################################################

# Python Refresher

## Basic Data Structures

The most basic "thing" in python is called an "object".  Basically anything you imagine as "data" would be represented by some number of Python objects.   Python provides several "built-in object types", like _integers_ and _strings_, which are useful for storing and manipulating various data.


The following table lists the fundamental Python object types.

| Type Abbreviation  | Type Full Name| Notes |
| ------------- | ------------- |-------------| 
| str | string  | Text |
| int | integer | Decimal-free numbers |
| float | Floating point Number | A decimal number |
| bool | Boolean | Can be either True or False |
| list | List | An indexed, ordered, collection of other types |
| dict| Dictionary | A 1-to-1 lookup table |
| set | Set | As in set-theory.  A collection of unique objects  |


The following cells show how to create objects of different types.

## Strings

In [19]:
# Strings are surrounded by quotes

s1 = 'This is a string'
s2 = "Double-quotes and single-quotes are equivalent"
s3 = '''This kind can span 
        many lines'''

print(s1)
print(s2) 
print(s3)

This is a string
Double-quotes and single-quotes are equivalent
This kind can span
        many lines

In [20]:
L1 = 'Luke. '
L2 = 'I am your father.'
print(L1+L2)

LAdd = L1 + L2

print(LAdd)

Luke. I am your father.
Luke. I am your father.

In [18]:
B0 = '99'
B1 = '98'
B2 = ' bottles of beer'
B3 = ' on the wall'
B4 = 'you take one down, pass it around'

print(B0+B2+B3)
print('\t'+B0+B2)           # '\t' is a tab character
print(B4+'\n'+'\t'+B0+B2+B3)# '\n' is a newline character

99 bottles of beer on the wall
	99 bottles of beer
you take one down, pass it around
	99 bottles of beer on the wall

In [ ]:
##################################################################################################################
# YouDo
# In a similar pattern to the cell above, make a set of print statements 
# which makes the final verse of that song.
# 
# In case you didn't grow up in North America:
#   https://en.wikipedia.org/wiki/99_Bottles_of_Beer
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################



#######################################   END STUDENT CODE   #####################################################

## Integers

In [22]:
A = 3      # type is inferred by lack of decimal point
B = int(3) # explicitly typed
C = int('3') # Casting a numeral 3, to the integer value of 3

print(A, B, C)

3 3 3

In [28]:
##################################################################################################################
#
# YouDo:
#    1) Fix the code below so it computes and prints 30 as the answer
#       Hint:  I can do it by deleting 2 characters and adding 2 more
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################

two = 2
three = 3

answer = two * three + 'two' * three
print(answer)


#######################################   END STUDENT CODE   #####################################################

30

## Floats

In [41]:
F0 = 3           # Not a float!
print('F0: ', F0, type(F0))

F1 = float(3)    # Cast to a float!
print('F1: ', F1, type(F1))

F2 = 3 + 0.0     # Added to a float
print('F2: ', F2, type(F2))

F3 = 3.         # A dot on the end makes it a float
print('F3: ', F3, type(F3))

F4 = 3.000      # So does adding decimapl places
print('F4: ', F4, type(F4))

F5 = 1e6-999997 # Scientific notation is a float as well
print('F5: ', F5, type(F5))

F6 = float('inf') # infinity is a float
print('F6: ', F6, type(F6))
#print(F6 + 1)

F7 = float('NaN') # not a number (nan) is a float, too
print('F7: ', F7, type(F7))

F0:  3 <class 'int'>
F1:  3.0 <class 'float'>
F2:  3.0 <class 'float'>
F3:  3.0 <class 'float'>
F4:  3.0 <class 'float'>
F5:  3.0 <class 'float'>
F6:  inf <class 'float'>
F7:  nan <class 'float'>

In [49]:
##################################################################################################################
#
# YouDo:
#    1) Fix the code below so it computes and prints 9.0 (a float) as the answer
#       Hint:  I can do it by deleting a single character
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################

two = 2
three = 3

answer = two * three + three
print('My answer is: ', answer, ' of type ', type(answer))




#######################################   END STUDENT CODE   #####################################################

My answer is:  9  of type  <class 'int'>

In [ ]:
## Very Useful Libraries

### Numerical Python (numpy)
### Regular Expressions (re)
### Scientific Python (scipy)
    #### Statsmodels
    #### Statistics
    #### Signals
    ### Sci-Kit Learn (sklearn

In [ ]:
)
### Pandas

In [ ]:
##################################################################################################################
#
# YouDo:
#    1) Print the first, "header" row of the data set
#    2) Print lines 37-40 of the actual data
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################

# 1) 
#print(lines[0])
# 2) 

print(lines[37:41])
#######################################   END STUDENT CODE   #####################################################